export type EmailTemplate = {
  key: string;
  kind: "marketing" | "abandoned_checkout" | "abandoned_cart" | "transactional";
  subject: string;
  preview: string;
  heading: string;
  body: string;
  ctaLabel: string;
  ctaPath: string;
  audience: string;
};

const marketing: EmailTemplate[] = [
  { key: "welcome-local-services", kind: "marketing", subject: "A simpler way to hire local help", preview: "Meet VeroTask and book with a clearer paper trail.", heading: "Local help, with fewer unknowns", body: "When something needs to get done, you should be able to see who you are hiring, what you are booking and what happens if there is a problem. VeroTask brings the service, payment and documented completion into one place.", ctaLabel: "Find local services", ctaPath: "/services", audience: "customers" },
  { key: "verified-work", kind: "marketing", subject: "What does ‘verified work’ actually mean?", preview: "A completed job should leave a useful record.", heading: "A click is not proof of a completed job", body: "Depending on the service, VeroTask can connect check-in, timestamps, customer PIN, before-and-after photos and a checklist to the booking. That creates a clearer record for both customer and provider.", ctaLabel: "See how protection works", ctaPath: "/protection", audience: "customers" },
  { key: "airbnb-cleaning", kind: "marketing", subject: "Your next vacation-rental turnover, organized", preview: "Cleaning records that help hosts stay in control.", heading: "Turnovers move fast. Your records should keep up.", body: "Use VeroTask to compare local vacation-rental cleaners, book the service and keep completion evidence tied to the job. It is especially useful when you manage a property from another city or country.", ctaLabel: "Find Airbnb cleaners", ctaPath: "/services?q=Vacation%20Rental%20Cleaning", audience: "customers" },
  { key: "pool-service", kind: "marketing", subject: "Pool service without the guesswork", preview: "Find local pool professionals and keep the booking history together.", heading: "Keep pool service visible", body: "Routine pool care is easier to manage when dates, provider, service details and completion history are all connected. Search local pool professionals across Central Florida.", ctaLabel: "Find pool service", ctaPath: "/services?q=Pool%20Service", audience: "customers" },
  { key: "hvac-ready", kind: "marketing", subject: "Florida heat does not wait for HVAC problems", preview: "Know where to look before you need help fast.", heading: "Have an HVAC option ready", body: "When cooling stops, comparing providers becomes urgent. VeroTask gives you one place to find local HVAC services, review the service and preserve a booking record.", ctaLabel: "Find HVAC professionals", ctaPath: "/services?q=HVAC", audience: "customers" },
  { key: "plumbing-fast", kind: "marketing", subject: "Need a plumber? Start with a clear booking", preview: "Service details, payment and history in one place.", heading: "Plumbing problems are stressful enough", body: "Search local plumbers, understand the booked service before paying and keep the resulting service history together if you need to review what happened later.", ctaLabel: "Find plumbers", ctaPath: "/services?q=Plumbing", audience: "customers" },
  { key: "handyman-list", kind: "marketing", subject: "That home repair list is not getting shorter", preview: "Turn small projects into a scheduled service.", heading: "One list. One booked professional.", body: "From mounting and assembly to small repairs, a handyman can clear several items in one visit. Compare local providers and choose a service that fits the work you need done.", ctaLabel: "Find a handyman", ctaPath: "/services?q=Handyman", audience: "customers" },
  { key: "pest-control", kind: "marketing", subject: "Do not let a small pest problem become a bigger one", preview: "Find local pest-control options in Central Florida.", heading: "Handle pest issues early", body: "Florida homes face year-round pest pressure. Search local professionals and keep your appointment, payment and service record connected in VeroTask.", ctaLabel: "Find pest control", ctaPath: "/services?q=Pest%20Control", audience: "customers" },
  { key: "lawn-care", kind: "marketing", subject: "A better way to stay ahead of lawn care", preview: "Local lawn professionals, one searchable marketplace.", heading: "Keep the outside of your property on schedule", body: "Whether you live locally or manage a second home, VeroTask helps you find lawn-care providers and retain the history of booked work.", ctaLabel: "Find lawn care", ctaPath: "/services?q=Lawn%20Care", audience: "customers" },
  { key: "pressure-washing", kind: "marketing", subject: "Give the exterior a reset", preview: "Pressure washing can change how a property looks in one visit.", heading: "A cleaner exterior starts with the right service", body: "Driveways, patios, pool decks and exterior surfaces collect Florida grime fast. Compare local pressure-washing providers and book with a clear record.", ctaLabel: "Find pressure washing", ctaPath: "/services?q=Pressure%20Washing", audience: "customers" },
  { key: "appliance-repair", kind: "marketing", subject: "Before replacing an appliance, check repair options", preview: "Local appliance repair can be worth comparing first.", heading: "Repair may be the smarter first step", body: "A refrigerator, washer or dryer problem does not always mean replacement. Search local appliance-repair professionals and compare your options.", ctaLabel: "Find appliance repair", ctaPath: "/services?q=Appliance%20Repair", audience: "customers" },
  { key: "moving-help", kind: "marketing", subject: "Moving day needs fewer surprises", preview: "Find local moving help and keep the booking details together.", heading: "Plan the help before the boxes pile up", body: "Whether you need a full move or help with heavy items, use VeroTask to search local moving services and keep the booking record in one place.", ctaLabel: "Find moving help", ctaPath: "/services?q=Moving", audience: "customers" },
  { key: "junk-removal", kind: "marketing", subject: "Ready to clear out what you no longer need?", preview: "Junk removal can free space quickly.", heading: "Clear the space, not your schedule", body: "Garage, rental turnover, renovation debris or unwanted furniture: compare local junk-removal options and book the service without chasing scattered messages.", ctaLabel: "Find junk removal", ctaPath: "/services?q=Junk%20Removal", audience: "customers" },
  { key: "furniture-assembly", kind: "marketing", subject: "Furniture arrived. Now comes the assembly.", preview: "Get local help for the part nobody looks forward to.", heading: "Skip the instruction-manual marathon", body: "Find local furniture-assembly professionals for beds, desks, shelving and more, with the booking and service record kept together.", ctaLabel: "Find assembly help", ctaPath: "/services?q=Furniture%20Assembly", audience: "customers" },
  { key: "locksmith", kind: "marketing", subject: "Save a locksmith search before you need one", preview: "Urgent situations are easier when you know where to look.", heading: "Locked out is not the time to start researching", body: "VeroTask gives you a place to find local locksmith services and review the provider and booking details before the work begins when circumstances allow.", ctaLabel: "Find locksmiths", ctaPath: "/services?q=Locksmith", audience: "customers" },
  { key: "weekend-projects", kind: "marketing", subject: "What could you finally get done this weekend?", preview: "Turn the project you keep postponing into a booked service.", heading: "A free weekend should not become a repair marathon", body: "Use VeroTask to find help for home maintenance, assembly, lawn care, cleaning and other local projects so your time can stay yours.", ctaLabel: "Browse services", ctaPath: "/services", audience: "customers" },
  { key: "vacation-rental-turnover", kind: "marketing", subject: "A turnover record you can review from anywhere", preview: "Useful for vacation-rental owners and managers.", heading: "You do not have to be on-site to stay informed", body: "For supported services, VeroTask can keep timestamps, checklist and photo evidence connected to the booking, giving remote property owners a more useful service trail.", ctaLabel: "Explore turnover cleaning", ctaPath: "/services?q=Vacation%20Rental%20Cleaning", audience: "customers" },
  { key: "florida-summer-home", kind: "marketing", subject: "Florida summer home checklist: cooling, pool, lawn", preview: "Three systems that demand attention in hot weather.", heading: "Prepare the property before the heat decides for you", body: "HVAC, pool care and lawn maintenance are high-frequency Florida needs. VeroTask helps you keep providers and service history organized across each category.", ctaLabel: "Check local services", ctaPath: "/services", audience: "customers" },
  { key: "review-powered-trust", kind: "marketing", subject: "Why verified booking reviews matter", preview: "A review is more useful when it is tied to real marketplace activity.", heading: "Reviews should come from real service history", body: "VeroTask reviews are designed to be connected to completed bookings. That helps customers compare providers using feedback grounded in actual marketplace transactions.", ctaLabel: "Browse providers", ctaPath: "/services", audience: "customers" },
  { key: "payment-protection", kind: "marketing", subject: "What happens after a provider marks a job complete?", preview: "The customer protection window is designed to prevent blind payout.", heading: "Completion is a process, not just a button", body: "After provider completion, the customer has a protection window to confirm the service or report a problem. Eligible bookings can then complete according to the evidence and platform rules.", ctaLabel: "Read the protection rules", ctaPath: "/protection", audience: "customers" },
  { key: "how-verotask-works", kind: "marketing", subject: "VeroTask in four steps", preview: "Find, book, verify and complete.", heading: "Local services with a clearer workflow", body: "Find a provider, book and pay through the marketplace, retain appropriate service evidence and confirm completion or raise a problem. The goal is simple: fewer gaps in the story of what happened.", ctaLabel: "See available services", ctaPath: "/services", audience: "customers" },
  { key: "book-again", kind: "marketing", subject: "Need another local service?", preview: "Your next booking can start from one marketplace.", heading: "Keep your property work organized", body: "If one job is finished, another may already be waiting. Browse VeroTask for cleaning, pool, HVAC, plumbing, handyman and other local services.", ctaLabel: "Book another service", ctaPath: "/services", audience: "customers" },
  { key: "home-maintenance-checklist", kind: "marketing", subject: "A practical Central Florida home-maintenance check", preview: "Pool, cooling, exterior, lawn and appliances.", heading: "Five areas worth checking this month", body: "Review your HVAC performance, pool condition, lawn schedule, exterior surfaces and major appliances. If something needs attention, compare a local professional before it becomes urgent.", ctaLabel: "Browse maintenance services", ctaPath: "/services", audience: "customers" },
  { key: "storm-season-prep", kind: "marketing", subject: "Storm season: handle the small property issues first", preview: "Maintenance before severe weather can reduce last-minute stress.", heading: "Prepare what you can control", body: "Loose exterior items, drainage issues, minor repairs and overdue maintenance are easier to address before weather pressure increases local demand.", ctaLabel: "Find local help", ctaPath: "/services", audience: "customers" },
  { key: "we-miss-you", kind: "marketing", subject: "Still have something on the to-do list?", preview: "Come back when the next project is ready.", heading: "VeroTask is here when the next job comes up", body: "If you have not booked recently, your account and marketplace history can still help you pick up where you left off when you need local service again.", ctaLabel: "See what is available", ctaPath: "/services", audience: "lapsed_customers" },
  { key: "provider-pro", kind: "marketing", subject: "Could Pro reduce your VeroTask marketplace fee?", preview: "A lower marketplace rate for active providers.", heading: "Pro is built for providers gaining traction", body: "The Pro plan is $39/month and reduces the marketplace fee to 10% on completed bookings, while adding visibility and performance tools for an active local service business.", ctaLabel: "Review Pro", ctaPath: "/dashboard", audience: "providers" },
  { key: "provider-elite", kind: "marketing", subject: "For higher-volume providers: VeroTask Elite", preview: "Lower fees and deeper operating tools for growing teams.", heading: "When volume grows, the unit economics matter", body: "Elite is $99/month with a 7% marketplace fee on completed bookings and is designed for providers operating at higher volume or across multiple service areas.", ctaLabel: "Review Elite", ctaPath: "/dashboard", audience: "providers" },
  { key: "claim-your-profile", kind: "marketing", subject: "Is your business already listed on VeroTask?", preview: "Claim the profile before accepting marketplace bookings.", heading: "Turn a public listing into your verified provider profile", body: "If VeroTask already shows public information about your business, claiming the profile lets you verify ownership, complete Stripe onboarding and control bookable services.", ctaLabel: "Find your business", ctaPath: "/services", audience: "providers" },
  { key: "provider-proof-wins", kind: "marketing", subject: "Good service records protect providers too", preview: "Evidence is not only for customer complaints.", heading: "Documented work helps both sides", body: "Check-in, customer PIN, photos and checklist evidence can strengthen the record when a provider performed the agreed service and a later dispute arises.", ctaLabel: "Read provider protection", ctaPath: "/protection", audience: "providers" },
  { key: "monthly-marketplace-update", kind: "marketing", subject: "Your VeroTask monthly marketplace update", preview: "New service activity and a reminder of what the platform protects.", heading: "One marketplace. A clearer service history.", body: "This month, review your recent service needs, provider history and any open property tasks. VeroTask keeps expanding its local-service marketplace across Central Florida.", ctaLabel: "Open VeroTask", ctaPath: "/", audience: "all_marketable" }
];

const abandonedCheckout: EmailTemplate[] = [
  { key: "abandoned-checkout-1", kind: "abandoned_checkout", subject: "Your VeroTask booking is not complete yet", preview: "You can return to the service you were booking.", heading: "You stopped before payment was completed", body: "Your service selection is still associated with your VeroTask activity. If you still want the appointment, return to VeroTask and review the provider, schedule and price before completing payment.", ctaLabel: "Return to booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-2", kind: "abandoned_checkout", subject: "Still need that local service?", preview: "Your unfinished booking may still be worth completing.", heading: "The job is still on your list", body: "If you left checkout because you were comparing options or got interrupted, you can return and continue when you are ready. Availability can change, so confirm the schedule again before payment.", ctaLabel: "Continue in VeroTask", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-3", kind: "abandoned_checkout", subject: "A reminder about your unfinished VeroTask checkout", preview: "Review the service before the booking expires.", heading: "One day later, your booking is still unfinished", body: "No payment has been completed for this booking. If you no longer need it, you can ignore this message. If you do, return to VeroTask and confirm the current service details.", ctaLabel: "Review booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-4", kind: "abandoned_checkout", subject: "Do you want to finish this booking?", preview: "We will not treat an unfinished checkout as a paid appointment.", heading: "Your service was never charged", body: "VeroTask does not treat an abandoned checkout as a completed booking. If you still need the service, start from your booking history and confirm current availability before paying.", ctaLabel: "See booking history", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-5", kind: "abandoned_checkout", subject: "Last reminder about this unfinished booking", preview: "Return if you still need the service; otherwise no action is needed.", heading: "Closing the recovery sequence", body: "This is the final automated reminder for this unfinished checkout. No payment was completed. You can still search VeroTask later whenever you need local help.", ctaLabel: "Browse services", ctaPath: "/services", audience: "abandoned_checkout" }
];

const abandonedCart: EmailTemplate[] = [
  { key: "abandoned-cart-1", kind: "abandoned_cart", subject: "You were looking at a VeroTask service", preview: "Pick up where you left off.", heading: "Still comparing local help?", body: "You viewed a service but did not move through checkout. If the job is still on your list, come back to compare the provider and current availability.", ctaLabel: "Continue browsing", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-2", kind: "abandoned_cart", subject: "Need help choosing a provider?", preview: "Use service details and verified booking history to compare.", heading: "A little comparison can prevent a rushed choice", body: "Return to VeroTask to compare available local professionals, service details and marketplace protections before booking.", ctaLabel: "Compare providers", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-3", kind: "abandoned_cart", subject: "That service is still waiting on your to-do list", preview: "No booking was created yet.", heading: "You have not booked anything yet", body: "Your earlier browsing did not create a paid appointment. If you still need the service, return to VeroTask and start a booking when you are ready.", ctaLabel: "Find the service again", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-4", kind: "abandoned_cart", subject: "Before the project gets postponed again", preview: "Turn the task into a scheduled service.", heading: "Ready to move the task off your list?", body: "If the project still matters, compare local options and choose a time that works. If not, there is nothing you need to do.", ctaLabel: "Browse local help", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-5", kind: "abandoned_cart", subject: "Final reminder: your VeroTask service search", preview: "Come back any time you need local help.", heading: "We will stop the recovery reminders here", body: "You did not create a paid booking from that visit. This is the final automated recovery email for it. VeroTask remains available whenever the project becomes a priority again.", ctaLabel: "Open VeroTask", ctaPath: "/", audience: "abandoned_cart" }
];

const transactional: EmailTemplate[] = [
  { key: "booking-thank-you", kind: "transactional", subject: "Thank you — your VeroTask payment was received", preview: "Your booking now has a marketplace payment record.", heading: "Your booking is paid", body: "Thank you for booking through VeroTask. Keep your booking page available for schedule details, the service PIN when applicable, completion evidence and the customer protection window.", ctaLabel: "Open booking", ctaPath: "/dashboard/bookings", audience: "customers" },
  { key: "provider-plan-thank-you", kind: "transactional", subject: "Welcome to your new VeroTask provider plan", preview: "Your provider subscription has been recorded.", heading: "Your VeroTask plan is active", body: "Thank you for investing in your VeroTask presence. Your plan and marketplace fee are tracked from Stripe subscription events so your billing status and provider economics stay auditable.", ctaLabel: "Open provider dashboard", ctaPath: "/dashboard", audience: "providers" }
];

export const EMAIL_TEMPLATES = [...marketing, ...abandonedCheckout, ...abandonedCart, ...transactional];

export function getEmailTemplate(key: string) {
  return EMAIL_TEMPLATES.find((template) => template.key === key) ?? null;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character] || character);
}

export function renderVeroTaskEmail(input: {
  template: EmailTemplate;
  firstName?: string | null;
  actionUrl?: string;
  unsubscribeUrl?: string | null;
  transactional?: boolean;
}) {
  const appUrl = (process.env.NEXT_PUBLIC_APP_URL || "https://verotask.com").replace(/\/$/, "");
  const actionUrl = input.actionUrl || `${appUrl}${input.template.ctaPath}`;
  const postal = process.env.MARKETING_POSTAL_ADDRESS || "VeroTask · Central Florida, USA";
  const greeting = input.firstName ? `Hi ${escapeHtml(input.firstName)},` : "Hello,";
  const unsubscribe = !input.transactional && input.unsubscribeUrl ? `<a href="${escapeHtml(input.unsubscribeUrl)}" style="color:#64748b;text-decoration:underline">Unsubscribe</a>` : "";

  return `<!doctype html><html><body style="margin:0;background:#f4f7f6;font-family:Arial,Helvetica,sans-serif;color:#10211b"><div style="display:none;max-height:0;overflow:hidden">${escapeHtml(input.template.preview)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f4f7f6;padding:32px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:white;border:1px solid #dde7e2;border-radius:22px;overflow:hidden"><tr><td style="padding:24px 28px;background:#0b2f25"><div style="font-size:22px;font-weight:800;color:white;letter-spacing:-.3px"><span style="display:inline-block;vertical-align:middle;width:30px;height:30px;line-height:30px;text-align:center;border-radius:9px;background:#6ee7b7;color:#0b2f25;margin-right:9px">✓</span>VeroTask</div><div style="margin-top:5px;color:#a7f3d0;font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase">Trusted local services. Verified work.</div></td></tr><tr><td style="padding:34px 28px"><p style="margin:0 0 18px;color:#475569;font-size:15px;line-height:24px">${greeting}</p><h1 style="margin:0;font-size:30px;line-height:37px;letter-spacing:-.8px">${escapeHtml(input.template.heading)}</h1><p style="margin:20px 0 0;color:#475569;font-size:16px;line-height:27px">${escapeHtml(input.template.body)}</p><p style="margin:30px 0 8px"><a href="${escapeHtml(actionUrl)}" style="display:inline-block;background:#126a4b;color:white;text-decoration:none;font-weight:800;padding:14px 20px;border-radius:12px">${escapeHtml(input.template.ctaLabel)}</a></p></td></tr><tr><td style="padding:22px 28px;border-top:1px solid #e7eeeb;color:#64748b;font-size:11px;line-height:18px"><strong style="color:#334155">VeroTask</strong><br>${escapeHtml(postal)}<br><span style="display:inline-block;margin-top:8px">${unsubscribe}${unsubscribe ? " · " : ""}<a href="${appUrl}/privacy" style="color:#64748b">Privacy</a> · <a href="${appUrl}/terms" style="color:#64748b">Terms</a></span></td></tr></table></td></tr></table></body></html>`;
}
