import { canonicalAppUrl } from "@/lib/app-url";

export type EmailTemplate = {
  key: string;
  kind: "marketing" | "abandoned_checkout" | "abandoned_cart" | "transactional";
  subject: string;
  preview: string;
  heading: string;
  body: string;
  ctaLabel: string;
  ctaPath: string;
  audience: string;
  benefits?: string[];
};

const marketing: EmailTemplate[] = [
  { key: "customer-intro-orlando", kind: "marketing", subject: "Meet VeroTask: local help across Orlando", preview: "A clearer way to find and book local professionals.", heading: "Local help without the guessing game", body: "VeroTask helps people in Orlando and Central Florida find nearby professionals, send a structured request, compare a quote and keep the booking process organized in one place.", benefits: ["Search local Pros by service and area", "No VeroTask booking fee before you accept a quote", "Track the request and booking in one place"], ctaLabel: "Find a local Pro", ctaPath: "/services", audience: "customers" },
  { key: "booking-fee-explained", kind: "marketing", subject: "How VeroTask payment actually works", preview: "The booking fee and service price are separate.", heading: "Know what you pay before you confirm", body: "The professional sends the service price. If you accept it, VeroTask charges only its booking fee. The service price is paid directly to the independent professional.", benefits: ["Clear separation of VeroTask fee and service price", "No service-price custody by VeroTask", "Booking confirmation after fee payment"], ctaLabel: "See how it works", ctaPath: "/how-it-works", audience: "customers" },
  { key: "find-local-pros-orlando", kind: "marketing", subject: "Looking for a local Pro in Orlando?", preview: "Search by service, city or ZIP code.", heading: "Start with Pros who serve your area", body: "Use VeroTask to search local professionals around Orlando and Central Florida. ZIP searches prioritize eligible nearby Pros and respect each professional's service radius.", benefits: ["Local service-radius matching", "City and ZIP search", "Nearby eligible Pros first"], ctaLabel: "Search Orlando services", ctaPath: "/locations/orlando-fl", audience: "customers" },
  { key: "need-help-fast", kind: "marketing", subject: "Need help soon? Send a clearer request", preview: "Give the Pro enough detail to answer faster.", heading: "A better request can lead to a faster answer", body: "Describe the job, preferred timing, ZIP code and key details before sending. VeroTask keeps your direct contact details and exact address private until the booking is confirmed.", benefits: ["Structured job brief", "Private direct contact before confirmation", "Track the Pro's response"], ctaLabel: "Start a request", ctaPath: "/services", audience: "customers" },
  { key: "home-repairs-orlando", kind: "marketing", subject: "Home repair help in Orlando starts here", preview: "Find local professionals for everyday repair needs.", heading: "When the house needs attention", body: "From small repairs to planned maintenance, VeroTask helps you find local service professionals and request a quote with the job details already organized.", benefits: ["Local professionals", "Structured quote request", "Clear booking history"], ctaLabel: "Find home services", ctaPath: "/services?q=Home%20Repair&location=Orlando%2C%20FL", audience: "customers" },
  { key: "cleaning-orlando", kind: "marketing", subject: "Need cleaning help in Central Florida?", preview: "Search local cleaning professionals and request a quote.", heading: "Make the cleaning request clear from the start", body: "Tell the Pro what type of cleaning you need, the approximate scope and preferred time. VeroTask keeps the request organized while you wait for the quote.", benefits: ["Clear scope before the quote", "Local Orlando-area search", "No booking fee while waiting"], ctaLabel: "Find cleaning Pros", ctaPath: "/services?q=Cleaning&location=Orlando%2C%20FL", audience: "customers" },
  { key: "moving-assembly", kind: "marketing", subject: "Furniture assembly or moving help?", preview: "Find local help for the jobs that need extra hands.", heading: "Some jobs are easier with the right hands", body: "Use VeroTask to look for local professionals for furniture assembly, moving-related tasks and other practical home services around Central Florida.", benefits: ["Search nearby Pros", "Describe size and timing", "Compare before confirming"], ctaLabel: "Search local help", ctaPath: "/services?q=Furniture%20Assembly", audience: "customers" },
  { key: "yard-outdoor", kind: "marketing", subject: "Outdoor work on your list?", preview: "Find local help for yard and exterior tasks.", heading: "Get the outdoor list moving", body: "Describe the task, service area and preferred timing, then compare local professionals who serve your ZIP code.", benefits: ["ZIP-based matching", "Service-radius filtering", "Clear request details"], ctaLabel: "Find outdoor services", ctaPath: "/services?q=Yard", audience: "customers" },
  { key: "pool-home-care", kind: "marketing", subject: "Keep recurring home care organized", preview: "One place to find local Pros and keep booking records.", heading: "Routine service should still be easy to track", body: "For recurring home needs such as pool care and maintenance, VeroTask keeps requests, quotes and booking records connected to the same account.", benefits: ["Booking history in your account", "Local service discovery", "Clear request status"], ctaLabel: "Explore local services", ctaPath: "/services", audience: "customers" },
  { key: "rental-host", kind: "marketing", subject: "Managing a rental property around Orlando?", preview: "Find local service help even when you are not nearby.", heading: "Local help for property tasks", body: "VeroTask can help hosts and property owners find professionals serving the Orlando area and keep the request and booking workflow visible from one account.", benefits: ["Useful for remote property owners", "Local service-area matching", "Track booking status online"], ctaLabel: "Find local services", ctaPath: "/services", audience: "customers" },
  { key: "safe-booking", kind: "marketing", subject: "What VeroTask protects before a booking", preview: "Direct contact and exact address stay private before confirmation.", heading: "Share less before you confirm", body: "Before the booking fee is paid, the Pro sees the job brief and service area, not your direct email, phone or exact street address. The exact address is released only after the booking is confirmed.", benefits: ["Exact address withheld before confirmation", "Direct contact details protected", "Structured marketplace flow"], ctaLabel: "Read protection rules", ctaPath: "/protection", audience: "customers" },
  { key: "arrival-verification", kind: "marketing", subject: "How VeroTask verifies that a Pro arrived", preview: "Geolocation plus your PIN or direct confirmation.", heading: "Arrival can be tied to the booking", body: "For a confirmed booking, VeroTask can verify provider arrival using geolocation near the service address together with your service PIN or your direct arrival confirmation.", benefits: ["Booking-specific arrival record", "Customer PIN or direct confirmation", "Arrival is not a claim about workmanship"], ctaLabel: "See protection details", ctaPath: "/protection", audience: "customers" },
  { key: "compare-pros", kind: "marketing", subject: "Compare local Pros before you decide", preview: "Distance, service area, profile and history can help.", heading: "You do not have to choose blindly", body: "VeroTask helps you compare local profiles and service-area eligibility before you send or confirm a request.", benefits: ["Local profile comparison", "Service-area context", "Quote before booking fee"], ctaLabel: "Compare local Pros", ctaPath: "/services", audience: "customers" },
  { key: "weekend-planning", kind: "marketing", subject: "Planning a home task this week?", preview: "Send requests early and give Pros time to respond.", heading: "A little lead time helps", body: "If the job is not an emergency, send the request early. Many available Pros respond within about two hours during normal business hours, while nights and weekends may take longer.", benefits: ["Request status stays visible", "Email update when the Pro responds", "Compare another Pro if you need someone sooner"], ctaLabel: "Plan a service", ctaPath: "/services", audience: "customers" },
  { key: "customer-reengagement", kind: "marketing", subject: "Still have something on your to-do list?", preview: "VeroTask can help you look for a local Pro.", heading: "That task does not have to stay on the list", body: "Come back to VeroTask, describe what you need and search local professionals serving Orlando and Central Florida.", benefits: ["Search by task or service", "Use city or ZIP code", "Request a quote without paying first"], ctaLabel: "Find a Pro", ctaPath: "/services", audience: "lapsed_customers" },

  { key: "pro-intro-orlando", kind: "marketing", subject: "Meet VeroTask for local Pros", preview: "Receive structured local requests without paying to join.", heading: "A local marketplace built for independent Pros", body: "VeroTask connects customers with independent service professionals around Orlando and Central Florida. Create or claim your profile, define your service area and decide which requests you want to quote.", benefits: ["Free plan available", "You choose which work to quote", "Customer pays your service price directly to you"], ctaLabel: "Join VeroTask", ctaPath: "/providers/join", audience: "providers" },
  { key: "pro-free-join", kind: "marketing", subject: "You can join VeroTask without a monthly fee", preview: "Start on Free and decide later if an upgrade makes sense.", heading: "Start with the work, not a subscription", body: "The Free plan has no monthly fee. You can build your profile, services and availability first, then evaluate paid plans only if they fit your business.", benefits: ["$0 monthly Free plan", "Control your services", "Optional upgrades later"], ctaLabel: "Create my Pro profile", ctaPath: "/providers/join?plan=free", audience: "providers" },
  { key: "pro-local-leads", kind: "marketing", subject: "Local customers can request a quote from your profile", preview: "Structured requests help you decide before responding.", heading: "See more context before you quote", body: "A VeroTask request can include task, size, timing and service area before you decide whether to send a price. Exact customer contact and street address remain protected until confirmation.", benefits: ["Structured job request", "Customer context before quoting", "No obligation to accept every request"], ctaLabel: "See the Pro experience", ctaPath: "/providers", audience: "providers" },
  { key: "pro-quote-fast", kind: "marketing", subject: "Fast responses can help win local work", preview: "Customers are waiting after they send a request.", heading: "A quick, clear quote matters", body: "When possible, VeroTask encourages Pros to review new requests within about two business hours. A fast answer helps the customer decide whether to wait, confirm or compare another Pro.", benefits: ["Email alert for new requests", "Quote through VeroTask", "Customer sees the response status"], ctaLabel: "Open my dashboard", ctaPath: "/dashboard", audience: "providers" },
  { key: "pro-profile-photo", kind: "marketing", subject: "A current Pro photo helps customers recognize you", preview: "Claimed Pros add a recent face photo to their profile.", heading: "Help the customer know who to expect", body: "Claimed VeroTask Pros add a recent face photo so the customer can recognize the professional expected to arrive. It is a recognition feature, not biometric identity verification.", benefits: ["Current face photo on the profile", "Helps arrival recognition", "Prior versions may be retained for safety and audit"], ctaLabel: "Complete my profile", ctaPath: "/dashboard", audience: "providers" },
  { key: "pro-service-radius", kind: "marketing", subject: "Set the service radius that actually works for you", preview: "VeroTask uses your location and radius to filter requests.", heading: "Do not waste time on jobs too far away", body: "Choose a service radius that fits your operation. VeroTask uses that radius when checking whether a customer location is eligible for your business.", benefits: ["5–50 mile service radius", "Distance-aware matching", "Fewer out-of-area requests"], ctaLabel: "Review my service area", ctaPath: "/dashboard", audience: "providers" },
  { key: "pro-availability", kind: "marketing", subject: "Keep your VeroTask availability current", preview: "A current schedule helps customers request realistic times.", heading: "Your schedule should work for your business", body: "Update weekly availability so VeroTask customers can request service times that better match when you actually work.", benefits: ["Weekly availability controls", "America/New_York scheduling", "You stay in control"], ctaLabel: "Update availability", ctaPath: "/dashboard", audience: "providers" },
  { key: "pro-reputation", kind: "marketing", subject: "Build a stronger local reputation over time", preview: "Real completed bookings can add useful marketplace history.", heading: "Consistency becomes visible", body: "Completed VeroTask bookings, ratings and reliability signals can strengthen your marketplace profile over time. The goal is to help customers make a more informed choice.", benefits: ["Ratings from real bookings", "Completed-job history", "Reliability signals over time"], ctaLabel: "View my Pro dashboard", ctaPath: "/dashboard", audience: "providers" },
  { key: "pro-plan-free", kind: "marketing", subject: "The Free plan may be all you need to start", preview: "No monthly fee, with a higher customer booking fee.", heading: "Start simple", body: "Free has no monthly subscription. The customer booking fee is higher than on Pro or Elite, so you can compare real activity before deciding whether a paid plan is worth it.", benefits: ["No monthly subscription", "Receive eligible requests", "Upgrade only when it makes business sense"], ctaLabel: "Review plans", ctaPath: "/providers#plans", audience: "providers" },
  { key: "pro-plan-upgrade", kind: "marketing", subject: "When does a paid VeroTask plan make sense?", preview: "Compare monthly cost with lower customer booking fees.", heading: "Upgrade based on numbers, not pressure", body: "Pro and Elite lower the customer booking-fee percentage and add business features. Review your activity and decide whether the monthly plan fits your volume.", benefits: ["Pro: lower customer booking fee", "Elite: lowest customer booking fee", "Keep Free if that is better for you"], ctaLabel: "Compare plans", ctaPath: "/providers#plans", audience: "providers" },
  { key: "pro-customer-rating", kind: "marketing", subject: "You can review customer reputation before accepting", preview: "The marketplace should give both sides useful context.", heading: "Trust should work both ways", body: "VeroTask shows customer reputation context to the Pro before the request is accepted, helping you make a more informed decision about the job.", benefits: ["Customer rating context", "Completed-service history", "You choose whether to quote"], ctaLabel: "Learn how jobs work", ctaPath: "/how-it-works", audience: "providers" },
  { key: "pro-central-florida-growth", kind: "marketing", subject: "Grow your local visibility across Central Florida", preview: "A complete VeroTask profile creates another local discovery point.", heading: "Be easier to discover where you actually work", body: "Complete your services, service radius, availability and profile information so customers searching Orlando and nearby Central Florida communities can understand what you offer.", benefits: ["Local city/service pages", "Service-radius matching", "Profile linked to real offerings"], ctaLabel: "Complete my profile", ctaPath: "/dashboard", audience: "providers" },

  { key: "marketplace-explainer", kind: "marketing", subject: "What VeroTask is, in one minute", preview: "A local marketplace connecting customers and independent Pros.", heading: "One goal: get the job done", body: "VeroTask helps customers find local professionals, send a structured request, receive a quote and coordinate the booking. Pros remain independent and the service price is paid directly to them.", benefits: ["Local marketplace for Central Florida", "Structured quote-and-booking flow", "Clear separation of platform fee and service price"], ctaLabel: "Explore VeroTask", ctaPath: "/", audience: "all_marketable" },
  { key: "orlando-community", kind: "marketing", subject: "VeroTask is focused on Orlando and Central Florida", preview: "Local first, not a generic global marketplace.", heading: "Built around a real local market", body: "VeroTask is focused on Orlando and selected Central Florida communities. As more active Pros join an area, local service and city pages expand with them.", benefits: ["Orlando-first marketplace", "Central Florida service areas", "Local Pros and local customers"], ctaLabel: "Explore Orlando", ctaPath: "/locations/orlando-fl", audience: "all_marketable" },
  { key: "security-trust", kind: "marketing", subject: "How to recognize an official VeroTask message", preview: "Know what VeroTask will and will not ask you for.", heading: "Keep marketplace communication safe", body: "Official account and booking links use verotask.online. VeroTask does not ask for your email password, gift cards, remote device access or banking credentials to verify a profile.", benefits: ["Official verotask.online links", "Passwordless customer/Pro sign-in", "Public security guidance"], ctaLabel: "Read security guidance", ctaPath: "/security", audience: "all_marketable" }
];

const abandonedCheckout: EmailTemplate[] = [
  { key: "abandoned-checkout-1", kind: "abandoned_checkout", subject: "Your next step toward a finished job", preview: "Pick up your accepted request and review the details.", heading: "One less thing on your to-do list.", body: "You have already found a professional and started payment. If you were interrupted, your booking page brings the service, price and requested time back together. Review the current details and complete payment when you are ready.", benefits: ["Your service and price in one place", "Only the VeroTask booking fee is paid through VeroTask", "A booking record you can return to"], ctaLabel: "Review my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-2", kind: "abandoned_checkout", subject: "A clearer plan before the work begins", preview: "Know the job, the professional and the next step.", heading: "Clarity makes the next step easier.", body: "Hiring local help should not mean piecing together scattered messages. Your VeroTask booking connects the agreed service, provider and payment history. Return to your booking to check that the details still fit your plans.", benefits: ["The provider accepts before you pay", "Private messages tied to your job", "A single place for schedule and service details"], ctaLabel: "See my service details", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-3", kind: "abandoned_checkout", subject: "What happens after your service is complete?", preview: "Your protection window is part of the booking.", heading: "Your confidence matters after payment, too.", body: "When the professional marks the work complete, you have a 24-hour protection window to confirm it or report a problem. Required service evidence stays with the booking, and an open dispute pauses booking completion while the evidence is reviewed. Read the protection rules and continue if the service is right for you.", benefits: ["A documented completion process", "Time to confirm or report a problem", "A clear dispute process when you need it"], ctaLabel: "Return to my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-4", kind: "abandoned_checkout", subject: "More time for the things you would rather do", preview: "Get the task moving without losing track of the details.", heading: "Make room for the rest of your day.", body: "That task may still be waiting, but organizing the next step does not need to take over your day. Revisit your booking, check the professional and schedule, and decide whether to continue. Availability can change; your booking page shows the current status.", benefits: ["Keep your home projects organized", "Review everything before you commit", "Find the job history whenever you need it"], ctaLabel: "Check my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-5", kind: "abandoned_checkout", subject: "Ready when your project is", preview: "Your final reminder for this unfinished checkout.", heading: "A useful next step, on your terms.", body: "This is the last reminder for this unfinished checkout. If the job is still a priority, return to review the current details and finish payment. If your plans changed, no action is needed. You can always come back to VeroTask for your next project.", benefits: ["A clear service and payment record", "Professional and customer accountability", "Local help when it fits your plans"], ctaLabel: "Review and continue", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" }
];

const abandonedCart: EmailTemplate[] = [
  { key: "abandoned-cart-1", kind: "abandoned_cart", subject: "You were looking at a VeroTask service", preview: "Pick up where you left off.", heading: "Still comparing local help?", body: "You viewed a service but did not move through checkout. If the job is still on your list, come back to compare the provider and current availability.", ctaLabel: "Continue browsing", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-2", kind: "abandoned_cart", subject: "Need help choosing a provider?", preview: "Use service details and verified booking history to compare.", heading: "A little comparison can prevent a rushed choice", body: "Return to VeroTask to compare available local professionals, service details and marketplace protections before booking.", ctaLabel: "Compare providers", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-3", kind: "abandoned_cart", subject: "That service is still waiting on your to-do list", preview: "No booking was created yet.", heading: "You have not booked anything yet", body: "Your earlier browsing did not create a paid appointment. If you still need the service, return to VeroTask and start a booking when you are ready.", ctaLabel: "Find the service again", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-4", kind: "abandoned_cart", subject: "Before the project gets postponed again", preview: "Turn the task into a scheduled service.", heading: "Ready to move the task off your list?", body: "If the project still matters, compare local options and choose a time that works. If not, there is nothing you need to do.", ctaLabel: "Browse local help", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-5", kind: "abandoned_cart", subject: "Final reminder: your VeroTask service search", preview: "Come back any time you need local help.", heading: "We will stop the recovery reminders here", body: "You did not create a paid booking from that visit. This is the final automated recovery email for it. VeroTask remains available whenever the project becomes a priority again.", ctaLabel: "Open VeroTask", ctaPath: "/", audience: "abandoned_cart" }
];

const transactional: EmailTemplate[] = [
  { key: "account-welcome", kind: "transactional", subject: "Welcome to VeroTask. Your account is ready.", preview: "Find local help and keep your service history together.", heading: "Good help starts here.", body: "Your VeroTask account is ready. You can find local professionals, request a service and follow your bookings in one place. If you offer services, create your provider profile and complete payment verification to get started.", ctaLabel: "Explore VeroTask", ctaPath: "/dashboard", audience: "all" },
  { key: "booking-thank-you", kind: "transactional", subject: "Thank you, your VeroTask payment was received", preview: "Your booking now has a marketplace payment record.", heading: "Your booking is paid", body: "Thank you for booking through VeroTask. Keep your booking page available for schedule details, the service PIN when applicable, completion evidence and the customer protection window.", ctaLabel: "Open booking", ctaPath: "/dashboard/bookings", audience: "customers" },
  { key: "provider-plan-thank-you", kind: "transactional", subject: "Welcome to your new VeroTask provider plan", preview: "Your provider subscription has been recorded.", heading: "Your VeroTask plan is active", body: "Thank you for investing in your VeroTask presence. Visit your dashboard to review your active plan, marketplace fee and billing details.", ctaLabel: "Open provider dashboard", ctaPath: "/dashboard", audience: "providers" }
];

const abandonedPlan: EmailTemplate[] = [
  { key: "abandoned-plan-1", kind: "abandoned_checkout", subject: "Your next step as a VeroTask professional", preview: "Review the provider plan you started choosing.", heading: "Build a business that is easier to manage.", body: "You started checking out a paid provider plan. Your billing page lets you compare the monthly price and marketplace fee before deciding. Your current plan stays in place until payment succeeds.", benefits: ["Review the complete plan price", "Compare marketplace fees", "Manage billing in your dashboard"], ctaLabel: "Review my plan", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-2", kind: "abandoned_checkout", subject: "What a lower marketplace fee means for your work", preview: "Compare the numbers for your own business.", heading: "Make the numbers work for you.", body: "Free has a 15% marketplace fee, Pro has a 10% fee with a $39 monthly subscription, and Elite has a 7% fee with a $99 monthly subscription. Review your expected paid work to decide whether the monthly plan makes sense for you.", benefits: ["Transparent monthly pricing", "Compare fees before subscribing", "Free remains available"], ctaLabel: "Compare my options", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-3", kind: "abandoned_checkout", subject: "Keep jobs, customers and payments together", preview: "A more organized next step for your service business.", heading: "Keep the service history in one place.", body: "VeroTask keeps requests, customer messages and payment records connected to the job. A paid plan changes your marketplace fee; review the plan details alongside the tools already available in your account before you continue.", benefits: ["One booking timeline", "Customer context for each job", "Clear billing records"], ctaLabel: "Open plans and billing", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-4", kind: "abandoned_checkout", subject: "Is a paid plan the right next step?", preview: "Choose based on the work you expect to complete.", heading: "Upgrade when it fits your business.", body: "A subscription is useful when its benefits and lower marketplace fee justify its monthly cost for your business. Return to billing to review the current terms, or keep your existing plan. A subscription does not guarantee jobs or replace provider verification.", benefits: ["Compare costs without guessing", "Review terms before paying", "Control your subscription"], ctaLabel: "Review the details", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-5", kind: "abandoned_checkout", subject: "Your final reminder about the provider plan", preview: "Continue whenever the timing is right.", heading: "Ready when your business is.", body: "This is the final reminder for this unfinished provider-plan checkout. If you are ready, open billing to review the price and complete payment. If your plans changed, there is nothing you need to do: an unfinished checkout does not activate a subscription.", benefits: ["Activation after successful payment", "Billing history in your account", "No more reminders for this checkout"], ctaLabel: "Return to my plan", ctaPath: "/dashboard", audience: "providers" }
];

export const EMAIL_TEMPLATES = [...marketing, ...abandonedCheckout, ...abandonedCart, ...abandonedPlan, ...transactional];

export function getEmailTemplate(key: string) {
  return EMAIL_TEMPLATES.find((template) => template.key === key) ?? null;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character] || character);
}

export function renderVeroTaskEmail(input: {
  template: EmailTemplate;
  firstName?: string | null;
  actionUrl?: string;
  unsubscribeUrl?: string | null;
  transactional?: boolean;
  trackingOpenUrl?: string | null;
  trackingClickUrl?: string | null;
}) {
  const appUrl = canonicalAppUrl();
  const actionUrl = input.trackingClickUrl || input.actionUrl || `${appUrl}${input.template.ctaPath}`;
  const postal = process.env.MARKETING_POSTAL_ADDRESS || "VeroTask · Central Florida, USA";
  const greeting = input.firstName ? `Hi ${escapeHtml(input.firstName)},` : "Hello,";
  const unsubscribe = !input.transactional && input.unsubscribeUrl ? `<a href="${escapeHtml(input.unsubscribeUrl)}" style="color:#64748b;text-decoration:underline">Unsubscribe</a>` : "";

  const benefits = input.template.benefits ?? ["Find local professionals", "Keep your service history together", "Understand the process before you book"];
  const links = [["Services", "/services"], ["How it works", "/how-it-works"], ["Protection", "/protection"], ["For professionals", "/providers"], ["Join VeroTask", "/providers/join"], ["Your account", "/dashboard"], ["Support", "/support"], ["Accessibility", "/accessibility"], ["Privacy", "/privacy"], ["Terms", "/terms"]];
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light"><title>${escapeHtml(input.template.subject)}</title><style>@media only screen and (max-width:640px){.vt-card{border-radius:0!important}.vt-pad{padding-left:20px!important;padding-right:20px!important}.vt-title{font-size:27px!important;line-height:33px!important}.vt-cta a{display:block!important;text-align:center!important}}</style></head>
<body style="margin:0;padding:0;background:#eef3f6;font-family:Arial,Helvetica,sans-serif;color:#102a3d">
<div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${escapeHtml(input.template.preview)}</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef3f6"><tr><td align="center" style="padding:32px 12px">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" class="vt-card" style="max-width:620px;background:#ffffff;border:1px solid #dbe4ec;border-radius:16px;overflow:hidden">
<tr><td class="vt-pad" style="padding:28px 28px 24px;background:#0a2a3d;border-bottom:4px solid #46b3df"><a href="${escapeHtml(appUrl)}" style="font-size:27px;font-weight:800;color:#ffffff;text-decoration:none;letter-spacing:-1px">VeroTask<span style="color:#7dd3fc">.</span></a><p style="margin:8px 0 0;color:#bae6fd;font-size:11px;letter-spacing:1.2px;text-transform:uppercase">Connecting Clients and Pros. One goal: get the job done.</p></td></tr>
<tr><td class="vt-pad" style="padding:32px 28px 12px"><p style="margin:0 0 18px;font-size:15px;color:#526576">${greeting}</p><h1 class="vt-title" style="margin:0;font-size:32px;line-height:39px;letter-spacing:-1px;color:#0a2a3d">${escapeHtml(input.template.heading)}</h1><p style="margin:22px 0 0;font-size:16px;line-height:27px;color:#465969">${escapeHtml(input.template.body)}</p></td></tr>
${input.transactional ? "" : `<tr><td style="padding:12px 28px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f7fb;border-radius:12px">${benefits.map((benefit) => `<tr><td width="28" style="padding:12px 0 12px 16px;color:#125674;font-weight:bold">✓</td><td style="padding:12px 16px 12px 4px;font-size:14px;line-height:21px;color:#123b56">${escapeHtml(benefit)}</td></tr>`).join("")}</table></td></tr>`}
<tr><td class="vt-pad vt-cta" style="padding:18px 28px 32px"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#123b56" style="border-radius:10px;mso-padding-alt:16px 24px"><a href="${escapeHtml(actionUrl)}" style="display:inline-block;padding:16px 24px;color:#ffffff;font-size:15px;font-weight:bold;line-height:20px;text-decoration:none;border-radius:10px">${escapeHtml(input.template.ctaLabel)} &rarr;</a></td></tr></table><p style="margin:20px 0 0;font-size:12px;line-height:19px;color:#526576">Need a hand? <a href="${escapeHtml(appUrl)}/support" style="color:#123b56;text-decoration:underline">Visit VeroTask support</a>.</p></td></tr>
<tr><td style="padding:26px 28px;border-top:1px solid #dbe4ec;background:#f8fafc"><p style="margin:0 0 12px;font-size:16px;font-weight:bold;color:#0a2a3d">Local help. A clearer way forward.</p><p style="margin:0;font-size:12px;line-height:25px">${links.map(([label, url]) => `<a href="${escapeHtml(appUrl + url)}" style="display:inline-block;margin-right:12px;color:#34556c;text-decoration:underline">${label}</a>`).join(" ")}</p><p style="margin:18px 0 0;font-size:11px;line-height:18px;color:#526576">${escapeHtml(postal)}<br>${input.transactional ? "This message concerns your VeroTask account or service." : "You are receiving this message because you opted in to VeroTask offers. You can stop promotional messages at any time."}</p>${unsubscribe ? `<p style="margin:12px 0 0;font-size:12px">${unsubscribe}</p>` : ""}<p style="margin:18px 0 0;color:#526576;font-size:11px">&copy; ${new Date().getFullYear()} VeroTask</p></td></tr>
${input.trackingOpenUrl ? `<img src="${escapeHtml(input.trackingOpenUrl)}" width="1" height="1" alt="" style="display:block;width:1px;height:1px;border:0;opacity:0" />` : ""}</table></td></tr></table></body></html>`;
}
