export type EmailTemplate = {
  key: string;
  kind: "marketing" | "abandoned_checkout" | "abandoned_cart" | "transactional";
  subject: string;
  preview: string;
  heading: string;
  body: string;
  ctaLabel: string;
  ctaPath: string;
  audience: string;
  benefits?: string[];
};

const marketing: EmailTemplate[] = [
  { key: "welcome-local-services", kind: "marketing", subject: "A simpler way to hire local help", preview: "Meet VeroTask and book with a clearer paper trail.", heading: "Local help, with fewer unknowns", body: "When something needs to get done, you should be able to see who you are hiring, what you are booking and what happens if there is a problem. VeroTask brings the service, payment and documented completion into one place.", ctaLabel: "Find local services", ctaPath: "/services", audience: "customers" },
  { key: "verified-work", kind: "marketing", subject: "What does ‘verified work’ actually mean?", preview: "A completed job should leave a useful record.", heading: "A click is not proof of a completed job", body: "Depending on the service, VeroTask can connect check-in, timestamps, customer PIN, before-and-after photos and a checklist to the booking. That creates a clearer record for both customer and provider.", ctaLabel: "See how protection works", ctaPath: "/protection", audience: "customers" },
  { key: "airbnb-cleaning", kind: "marketing", subject: "Your next vacation-rental turnover, organized", preview: "Cleaning records that help hosts stay in control.", heading: "Turnovers move fast. Your records should keep up.", body: "Use VeroTask to compare local vacation-rental cleaners, book the service and keep completion evidence tied to the job. It is especially useful when you manage a property from another city or country.", ctaLabel: "Find Airbnb cleaners", ctaPath: "/services?q=Vacation%20Rental%20Cleaning", audience: "customers" },
  { key: "pool-service", kind: "marketing", subject: "Pool service without the guesswork", preview: "Find local pool professionals and keep the booking history together.", heading: "Keep pool service visible", body: "Routine pool care is easier to manage when dates, provider, service details and completion history are all connected. Pesquise profissionais locais de piscina na sua região.", ctaLabel: "Find pool service", ctaPath: "/services?q=Pool%20Service", audience: "customers" },
  { key: "hvac-ready", kind: "marketing", subject: "Florida heat does not wait for HVAC problems", preview: "Know where to look before you need help fast.", heading: "Have an HVAC option ready", body: "When cooling stops, comparing providers becomes urgent. VeroTask gives you one place to find local HVAC services, review the service and preserve a booking record.", ctaLabel: "Find HVAC professionals", ctaPath: "/services?q=HVAC", audience: "customers" },
  { key: "plumbing-fast", kind: "marketing", subject: "Need a plumber? Start with a clear booking", preview: "Service details, payment and history in one place.", heading: "Plumbing problems are stressful enough", body: "Search local plumbers, understand the booked service before paying and keep the resulting service history together if you need to review what happened later.", ctaLabel: "Find plumbers", ctaPath: "/services?q=Plumbing", audience: "customers" },
  { key: "handyman-list", kind: "marketing", subject: "That home repair list is not getting shorter", preview: "Turn small projects into a scheduled service.", heading: "One list. One booked professional.", body: "From mounting and assembly to small repairs, a handyman can clear several items in one visit. Compare local providers and choose a service that fits the work you need done.", ctaLabel: "Find a handyman", ctaPath: "/services?q=Handyman", audience: "customers" },
  { key: "pest-control", kind: "marketing", subject: "Do not let a small pest problem become a bigger one", preview: "Encontre opções locais de controle de pragas.", heading: "Handle pest issues early", body: "Casas precisam de atenção constante contra pragas. Pesquise profissionais locais e mantenha seu agendamento e histórico de serviço conectados na VeroTask.", ctaLabel: "Find pest control", ctaPath: "/services?q=Pest%20Control", audience: "customers" },
  { key: "lawn-care", kind: "marketing", subject: "A better way to stay ahead of lawn care", preview: "Local lawn professionals, one searchable marketplace.", heading: "Keep the outside of your property on schedule", body: "Whether you live locally or manage a second home, VeroTask helps you find lawn-care providers and retain the history of booked work.", ctaLabel: "Find lawn care", ctaPath: "/services?q=Lawn%20Care", audience: "customers" },
  { key: "pressure-washing", kind: "marketing", subject: "Give the exterior a reset", preview: "Pressure washing can change how a property looks in one visit.", heading: "A cleaner exterior starts with the right service", body: "Driveways, patios, pool decks and exterior surfaces collect Florida grime fast. Compare local pressure-washing providers and book with a clear record.", ctaLabel: "Find pressure washing", ctaPath: "/services?q=Pressure%20Washing", audience: "customers" },
  { key: "appliance-repair", kind: "marketing", subject: "Before replacing an appliance, check repair options", preview: "Local appliance repair can be worth comparing first.", heading: "Repair may be the smarter first step", body: "A refrigerator, washer or dryer problem does not always mean replacement. Search local appliance-repair professionals and compare your options.", ctaLabel: "Find appliance repair", ctaPath: "/services?q=Appliance%20Repair", audience: "customers" },
  { key: "moving-help", kind: "marketing", subject: "Moving day needs fewer surprises", preview: "Find local moving help and keep the booking details together.", heading: "Plan the help before the boxes pile up", body: "Whether you need a full move or help with heavy items, use VeroTask to search local moving services and keep the booking record in one place.", ctaLabel: "Find moving help", ctaPath: "/services?q=Moving", audience: "customers" },
  { key: "junk-removal", kind: "marketing", subject: "Ready to clear out what you no longer need?", preview: "Junk removal can free space quickly.", heading: "Clear the space, not your schedule", body: "Garage, rental turnover, renovation debris or unwanted furniture: compare local junk-removal options and book the service without chasing scattered messages.", ctaLabel: "Find junk removal", ctaPath: "/services?q=Junk%20Removal", audience: "customers" },
  { key: "furniture-assembly", kind: "marketing", subject: "Furniture arrived. Now comes the assembly.", preview: "Get local help for the part nobody looks forward to.", heading: "Skip the instruction-manual marathon", body: "Find local furniture-assembly professionals for beds, desks, shelving and more, with the booking and service record kept together.", ctaLabel: "Find assembly help", ctaPath: "/services?q=Furniture%20Assembly", audience: "customers" },
  { key: "locksmith", kind: "marketing", subject: "Save a locksmith search before you need one", preview: "Urgent situations are easier when you know where to look.", heading: "Locked out is not the time to start researching", body: "VeroTask gives you a place to find local locksmith services and review the provider and booking details before the work begins when circumstances allow.", ctaLabel: "Find locksmiths", ctaPath: "/services?q=Locksmith", audience: "customers" },
  { key: "weekend-projects", kind: "marketing", subject: "What could you finally get done this weekend?", preview: "Turn the project you keep postponing into a booked service.", heading: "A free weekend should not become a repair marathon", body: "Use VeroTask to find help for home maintenance, assembly, lawn care, cleaning and other local projects so your time can stay yours.", ctaLabel: "Browse services", ctaPath: "/services", audience: "customers" },
  { key: "vacation-rental-turnover", kind: "marketing", subject: "A turnover record you can review from anywhere", preview: "Useful for vacation-rental owners and managers.", heading: "You do not have to be on-site to stay informed", body: "For supported services, VeroTask can keep timestamps, checklist and photo evidence connected to the booking, giving remote property owners a more useful service trail.", ctaLabel: "Explore turnover cleaning", ctaPath: "/services?q=Vacation%20Rental%20Cleaning", audience: "customers" },
  { key: "florida-summer-home", kind: "marketing", subject: "Florida summer home checklist: cooling, pool, lawn", preview: "Three systems that demand attention in hot weather.", heading: "Prepare the property before the heat decides for you", body: "HVAC, pool care and lawn maintenance are high-frequency Florida needs. VeroTask helps you keep providers and service history organized across each category.", ctaLabel: "Check local services", ctaPath: "/services", audience: "customers" },
  { key: "review-powered-trust", kind: "marketing", subject: "Why verified booking reviews matter", preview: "A review is more useful when it is tied to real marketplace activity.", heading: "Reviews should come from real service history", body: "VeroTask reviews are designed to be connected to completed bookings. That helps customers compare providers using feedback grounded in actual marketplace transactions.", ctaLabel: "Browse providers", ctaPath: "/services", audience: "customers" },
  { key: "payment-protection", kind: "marketing", subject: "What happens after a provider marks a job complete?", preview: "The customer protection window is designed to prevent blind payout.", heading: "Completion is a process, not just a button", body: "After provider completion, the customer has a protection window to confirm the service or report a problem. Eligible bookings can then complete according to the evidence and platform rules.", ctaLabel: "Read the protection rules", ctaPath: "/protection", audience: "customers" },
  { key: "how-verotask-works", kind: "marketing", subject: "VeroTask in four steps", preview: "Find, book, verify and complete.", heading: "Local services with a clearer workflow", body: "Find a provider, request a service, pay after the provider accepts, then confirm completion or report a problem. The goal is simple: fewer gaps in the story of what happened.", ctaLabel: "See available services", ctaPath: "/services", audience: "customers" },
  { key: "book-again", kind: "marketing", subject: "Need another local service?", preview: "Your next booking can start from one marketplace.", heading: "Keep your property work organized", body: "If one job is finished, another may already be waiting. Browse VeroTask for cleaning, pool, HVAC, plumbing, handyman and other local services.", ctaLabel: "Book another service", ctaPath: "/services", audience: "customers" },
  { key: "home-maintenance-checklist", kind: "marketing", subject: "Um checklist prático de manutenção residencial", preview: "Pool, cooling, exterior, lawn and appliances.", heading: "Five areas worth checking this month", body: "Review your HVAC performance, pool condition, lawn schedule, exterior surfaces and major appliances. If something needs attention, compare a local professional before it becomes urgent.", ctaLabel: "Browse maintenance services", ctaPath: "/services", audience: "customers" },
  { key: "storm-season-prep", kind: "marketing", subject: "Storm season: handle the small property issues first", preview: "Maintenance before severe weather can reduce last-minute stress.", heading: "Prepare what you can control", body: "Loose exterior items, drainage issues, minor repairs and overdue maintenance are easier to address before weather pressure increases local demand.", ctaLabel: "Find local help", ctaPath: "/services", audience: "customers" },
  { key: "we-miss-you", kind: "marketing", subject: "Still have something on the to-do list?", preview: "Come back when the next project is ready.", heading: "VeroTask is here when the next job comes up", body: "If you have not booked recently, your account and marketplace history can still help you pick up where you left off when you need local service again.", ctaLabel: "See what is available", ctaPath: "/services", audience: "lapsed_customers" },
  { key: "provider-pro", kind: "marketing", subject: "Could Pro reduce your VeroTask marketplace fee?", preview: "A lower marketplace rate for active providers.", heading: "Pro is built for providers gaining traction", body: "The Pro plan is $39/month and reduces the marketplace fee to 10% on completed bookings, with the service history and operating tools in your provider dashboard.", ctaLabel: "Review Pro", ctaPath: "/dashboard", audience: "providers" },
  { key: "provider-elite", kind: "marketing", subject: "For higher-volume providers: VeroTask Elite", preview: "Lower fees and deeper operating tools for growing teams.", heading: "When volume grows, the unit economics matter", body: "Elite is $99/month with a 7% marketplace fee on completed bookings and is designed for providers operating at higher volume or across multiple service areas.", ctaLabel: "Review Elite", ctaPath: "/dashboard", audience: "providers" },
  { key: "claim-your-profile", kind: "marketing", subject: "Is your business already listed on VeroTask?", preview: "Claim the profile before accepting marketplace bookings.", heading: "Turn a public listing into your verified provider profile", body: "If VeroTask already shows public information about your business, claiming the profile lets you verify ownership, complete o cadastro e controle seus serviços agendáveis.", ctaLabel: "Find your business", ctaPath: "/services", audience: "providers" },
  { key: "provider-proof-wins", kind: "marketing", subject: "Good service records protect providers too", preview: "Evidence is not only for customer complaints.", heading: "Documented work helps both sides", body: "Check-in, customer PIN, photos and checklist evidence can strengthen the record when a provider performed the agreed service and a later dispute arises.", ctaLabel: "Read provider protection", ctaPath: "/protection", audience: "providers" },
  { key: "monthly-marketplace-update", kind: "marketing", subject: "Your VeroTask monthly marketplace update", preview: "New service activity and a reminder of what the platform protects.", heading: "One marketplace. A clearer service history.", body: "This month, review your recent service needs, provider history and any open property tasks. A VeroTask continua expandindo seu marketplace de serviços locais.", ctaLabel: "Open VeroTask", ctaPath: "/", audience: "all_marketable" }
];

const abandonedCheckout: EmailTemplate[] = [
  { key: "abandoned-checkout-1", kind: "abandoned_checkout", subject: "Your next step toward a finished job", preview: "Pick up your accepted request and review the details.", heading: "One less thing on your to-do list.", body: "You have already found a professional and started payment. If you were interrupted, your booking page brings the service, price and requested time back together. Review the current details and complete payment when you are ready.", benefits: ["Your service and price in one place", "Payment stays inside VeroTask", "A booking record you can return to"], ctaLabel: "Review my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-2", kind: "abandoned_checkout", subject: "A clearer plan before the work begins", preview: "Know the job, the professional and the next step.", heading: "Clarity makes the next step easier.", body: "Hiring local help should not mean piecing together scattered messages. Your VeroTask booking connects the agreed service, provider and payment history. Return to your booking to check that the details still fit your plans.", benefits: ["The provider accepts before you pay", "Private messages tied to your job", "A single place for schedule and service details"], ctaLabel: "See my service details", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-3", kind: "abandoned_checkout", subject: "What happens after your service is complete?", preview: "Your protection window is part of the booking.", heading: "Your confidence matters after payment, too.", body: "When the professional marks the work complete, you have a 24-hour protection window to confirm it or report a problem. Required service evidence stays with the booking, and an open dispute pauses the normal provider payout. Read the protection rules and continue if the service is right for you.", benefits: ["A documented completion process", "Time to confirm or report a problem", "A clear dispute process when you need it"], ctaLabel: "Return to my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-4", kind: "abandoned_checkout", subject: "More time for the things you would rather do", preview: "Get the task moving without losing track of the details.", heading: "Make room for the rest of your day.", body: "That task may still be waiting, but organizing the next step does not need to take over your day. Revisit your booking, check the professional and schedule, and decide whether to continue. Availability can change; your booking page shows the current status.", benefits: ["Keep your home projects organized", "Review everything before you commit", "Find the job history whenever you need it"], ctaLabel: "Check my booking", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" },
  { key: "abandoned-checkout-5", kind: "abandoned_checkout", subject: "Ready when your project is", preview: "Your final reminder for this unfinished checkout.", heading: "A useful next step, on your terms.", body: "This is the last reminder for this unfinished checkout. If the job is still a priority, return to review the current details and finish payment. If your plans changed, no action is needed. You can always come back to VeroTask for your next project.", benefits: ["A clear service and payment record", "Professional and customer accountability", "Local help when it fits your plans"], ctaLabel: "Review and continue", ctaPath: "/dashboard/bookings", audience: "abandoned_checkout" }
];

const abandonedCart: EmailTemplate[] = [
  { key: "abandoned-cart-1", kind: "abandoned_cart", subject: "You were looking at a VeroTask service", preview: "Pick up where you left off.", heading: "Still comparing local help?", body: "You viewed a service but did not move through checkout. If the job is still on your list, come back to compare the provider and current availability.", ctaLabel: "Continue browsing", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-2", kind: "abandoned_cart", subject: "Need help choosing a provider?", preview: "Use service details and verified booking history to compare.", heading: "A little comparison can prevent a rushed choice", body: "Return to VeroTask to compare available local professionals, service details and marketplace protections before booking.", ctaLabel: "Compare providers", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-3", kind: "abandoned_cart", subject: "That service is still waiting on your to-do list", preview: "No booking was created yet.", heading: "You have not booked anything yet", body: "Your earlier browsing did not create a paid appointment. If you still need the service, return to VeroTask and start a booking when you are ready.", ctaLabel: "Find the service again", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-4", kind: "abandoned_cart", subject: "Before the project gets postponed again", preview: "Turn the task into a scheduled service.", heading: "Ready to move the task off your list?", body: "If the project still matters, compare local options and choose a time that works. If not, there is nothing you need to do.", ctaLabel: "Browse local help", ctaPath: "/services", audience: "abandoned_cart" },
  { key: "abandoned-cart-5", kind: "abandoned_cart", subject: "Final reminder: your VeroTask service search", preview: "Come back any time you need local help.", heading: "We will stop the recovery reminders here", body: "You did not create a paid booking from that visit. This is the final automated recovery email for it. VeroTask remains available whenever the project becomes a priority again.", ctaLabel: "Open VeroTask", ctaPath: "/", audience: "abandoned_cart" }
];

const transactional: EmailTemplate[] = [
  { key: "account-welcome", kind: "transactional", subject: "Welcome to VeroTask. Your account is ready.", preview: "Find local help and keep your service history together.", heading: "Good help starts here.", body: "Your VeroTask account is ready. You can find local professionals, request a service and follow your bookings in one place. If you offer services, create your provider profile and complete payment verification to get started.", ctaLabel: "Explore VeroTask", ctaPath: "/dashboard", audience: "all" },
  { key: "booking-thank-you", kind: "transactional", subject: "Thank you, your VeroTask payment was received", preview: "Your booking now has a marketplace payment record.", heading: "Your booking is paid", body: "Thank you for booking through VeroTask. Keep your booking page available for schedule details, the service PIN when applicable, completion evidence and the customer protection window.", ctaLabel: "Open booking", ctaPath: "/dashboard/bookings", audience: "customers" },
  { key: "provider-plan-thank-you", kind: "transactional", subject: "Welcome to your new VeroTask provider plan", preview: "Your provider subscription has been recorded.", heading: "Your VeroTask plan is active", body: "Thank you for investing in your VeroTask presence. Visit your dashboard to review your active plan, marketplace fee and billing details.", ctaLabel: "Open provider dashboard", ctaPath: "/dashboard", audience: "providers" }
];

const abandonedPlan: EmailTemplate[] = [
  { key: "abandoned-plan-1", kind: "abandoned_checkout", subject: "Your next step as a VeroTask professional", preview: "Review the provider plan you started choosing.", heading: "Build a business that is easier to manage.", body: "You started checking out a paid provider plan. Your billing page lets you compare the monthly price and marketplace fee before deciding. Your current plan stays in place until payment succeeds.", benefits: ["Review the complete plan price", "Compare marketplace fees", "Manage billing in your dashboard"], ctaLabel: "Review my plan", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-2", kind: "abandoned_checkout", subject: "What a lower marketplace fee means for your work", preview: "Compare the numbers for your own business.", heading: "Make the numbers work for you.", body: "Free has a 15% marketplace fee, Pro has a 10% fee with a $39 monthly subscription, and Elite has a 7% fee with a $99 monthly subscription. Review your expected paid work to decide whether the monthly plan makes sense for you.", benefits: ["Transparent monthly pricing", "Compare fees before subscribing", "Free remains available"], ctaLabel: "Compare my options", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-3", kind: "abandoned_checkout", subject: "Keep jobs, customers and payments together", preview: "A more organized next step for your service business.", heading: "Keep the service history in one place.", body: "VeroTask keeps requests, customer messages and payment records connected to the job. A paid plan changes your marketplace fee; review the plan details alongside the tools already available in your account before you continue.", benefits: ["One booking timeline", "Customer context for each job", "Clear billing records"], ctaLabel: "Open plans and billing", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-4", kind: "abandoned_checkout", subject: "Is a paid plan the right next step?", preview: "Choose based on the work you expect to complete.", heading: "Upgrade when it fits your business.", body: "A subscription is useful when its benefits and lower marketplace fee justify its monthly cost for your business. Return to billing to review the current terms, or keep your existing plan. A subscription does not guarantee jobs or replace provider verification.", benefits: ["Compare costs without guessing", "Review terms before paying", "Control your subscription"], ctaLabel: "Review the details", ctaPath: "/dashboard", audience: "providers" },
  { key: "abandoned-plan-5", kind: "abandoned_checkout", subject: "Your final reminder about the provider plan", preview: "Continue whenever the timing is right.", heading: "Ready when your business is.", body: "This is the final reminder for this unfinished provider-plan checkout. If you are ready, open billing to review the price and complete payment. If your plans changed, there is nothing you need to do: an unfinished checkout does not activate a subscription.", benefits: ["Activation after successful payment", "Billing history in your account", "No more reminders for this checkout"], ctaLabel: "Return to my plan", ctaPath: "/dashboard", audience: "providers" }
];

export const EMAIL_TEMPLATES = [...marketing, ...abandonedCheckout, ...abandonedCart, ...abandonedPlan, ...transactional];

export function getEmailTemplate(key: string) {
  return EMAIL_TEMPLATES.find((template) => template.key === key) ?? null;
}

function escapeHtml(value: string) {
  return value.replace(/[&<>"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character] || character);
}

export function renderVeroTaskEmail(input: {
  template: EmailTemplate;
  firstName?: string | null;
  actionUrl?: string;
  unsubscribeUrl?: string | null;
  transactional?: boolean;
}) {
  const appUrl = (process.env.NEXT_PUBLIC_APP_URL || "https://verotask.com").replace(/\/$/, "");
  const actionUrl = input.actionUrl || `${appUrl}${input.template.ctaPath}`;
  const postal = process.env.MARKETING_POSTAL_ADDRESS || "VeroTask · Brasil";
  const greeting = input.firstName ? `Hi ${escapeHtml(input.firstName)},` : "Hello,";
  const unsubscribe = !input.transactional && input.unsubscribeUrl ? `<a href="${escapeHtml(input.unsubscribeUrl)}" style="color:#64748b;text-decoration:underline">Unsubscribe</a>` : "";

  const benefits = input.template.benefits ?? ["Find local professionals", "Keep your service history together", "Understand the process before you book"];
  const links = [["Services", "/services"], ["How it works", "/how-it-works"], ["Protection", "/protection"], ["For professionals", "/providers"], ["Join VeroTask", "/providers/join"], ["Your account", "/dashboard"], ["Support", "/support"], ["Accessibility", "/accessibility"], ["Privacy", "/privacy"], ["Terms", "/terms"]];
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(input.template.subject)}</title></head>
<body style="margin:0;padding:0;background:#eef3f6;font-family:Arial,Helvetica,sans-serif;color:#102a3d">
<div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${escapeHtml(input.template.preview)}</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#eef3f6"><tr><td align="center" style="padding:32px 12px">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#ffffff;border:1px solid #dbe4ec;border-radius:16px;overflow:hidden">
<tr><td style="padding:28px 28px 24px;background:#0a2a3d;border-bottom:4px solid #46b3df"><a href="${escapeHtml(appUrl)}" style="font-size:27px;font-weight:800;color:#ffffff;text-decoration:none;letter-spacing:-1px">VeroTask<span style="color:#7dd3fc">.</span></a><p style="margin:8px 0 0;color:#bae6fd;font-size:11px;letter-spacing:1.5px;text-transform:uppercase">Trusted local services. Verified work.</p></td></tr>
<tr><td style="padding:32px 28px 12px"><p style="margin:0 0 18px;font-size:15px;color:#526576">${greeting}</p><h1 style="margin:0;font-size:32px;line-height:39px;letter-spacing:-1px;color:#0a2a3d">${escapeHtml(input.template.heading)}</h1><p style="margin:22px 0 0;font-size:16px;line-height:27px;color:#465969">${escapeHtml(input.template.body)}</p></td></tr>
${input.transactional ? "" : `<tr><td style="padding:12px 28px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f7fb;border-radius:12px">${benefits.map((benefit) => `<tr><td width="28" style="padding:12px 0 12px 16px;color:#125674;font-weight:bold">✓</td><td style="padding:12px 16px 12px 4px;font-size:14px;line-height:21px;color:#123b56">${escapeHtml(benefit)}</td></tr>`).join("")}</table></td></tr>`}
<tr><td style="padding:18px 28px 32px"><table role="presentation" cellspacing="0" cellpadding="0"><tr><td bgcolor="#123b56" style="border-radius:10px;mso-padding-alt:16px 24px"><a href="${escapeHtml(actionUrl)}" style="display:inline-block;padding:16px 24px;color:#ffffff;font-size:15px;font-weight:bold;line-height:20px;text-decoration:none;border-radius:10px">${escapeHtml(input.template.ctaLabel)} &rarr;</a></td></tr></table><p style="margin:20px 0 0;font-size:12px;line-height:19px;color:#526576">Need a hand? <a href="${escapeHtml(appUrl)}/support" style="color:#123b56;text-decoration:underline">Visit VeroTask support</a>.</p></td></tr>
<tr><td style="padding:26px 28px;border-top:1px solid #dbe4ec;background:#f8fafc"><p style="margin:0 0 12px;font-size:16px;font-weight:bold;color:#0a2a3d">Local help. A clearer way forward.</p><p style="margin:0;font-size:12px;line-height:25px">${links.map(([label, url]) => `<a href="${escapeHtml(appUrl + url)}" style="display:inline-block;margin-right:12px;color:#34556c;text-decoration:underline">${label}</a>`).join(" ")}</p><p style="margin:18px 0 0;font-size:11px;line-height:18px;color:#526576">${escapeHtml(postal)}<br>${input.transactional ? "This message concerns your VeroTask account or service." : "You are receiving this message because you opted in to VeroTask offers. You can stop promotional messages at any time."}</p>${unsubscribe ? `<p style="margin:12px 0 0;font-size:12px">${unsubscribe}</p>` : ""}<p style="margin:18px 0 0;color:#526576;font-size:11px">&copy; ${new Date().getFullYear()} VeroTask</p></td></tr>
</table></td></tr></table></body></html>`;
}
