import { desc, eq } from "drizzle-orm";
import { FileDown, Fingerprint, LockKeyhole, Scale, ShieldCheck } from "lucide-react";
import { redirect } from "next/navigation";
import { AdminShell } from "@/components/admin-shell";
import { getDb } from "@/db";
import { adminAuditEvents, auditExports, legalCases, legalHolds } from "@/db/analytics-schema";
import { isAdminSession } from "@/lib/admin-auth";
import { createLegalCase } from "./actions";

export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string; case?: string }> }) {
  if (!(await isAdminSession())) redirect("/admin/signin");
  const query = await searchParams;
  const db = getDb();
  const [cases, holds, exports, audit] = await Promise.all([
    db.select().from(legalCases).orderBy(desc(legalCases.openedAt)).limit(100),
    db.select().from(legalHolds).where(eq(legalHolds.active, true)).orderBy(desc(legalHolds.createdAt)).limit(200),
    db.select().from(auditExports).orderBy(desc(auditExports.generatedAt)).limit(100),
    db.select().from(adminAuditEvents).orderBy(desc(adminAuditEvents.occurredAt)).limit(100)
  ]);

  return (
    <AdminShell active="/admin/legal">
      <div className="mx-auto max-w-[1600px]">
        <div><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-300">Evidence governance</div><h1 className="mt-2 text-3xl font-black">Legal & Audit Center</h1><p className="mt-2 max-w-4xl text-sm leading-6 text-slate-500">Create preservation cases, place legal holds and export a hashed evidence package. Outside parties do not receive direct database access; VeroTask produces records through authorized process.</p></div>
        {query.notice && <div className="mt-5 rounded-xl border border-emerald-300/20 bg-emerald-300/5 p-3 text-sm font-bold text-emerald-200">Case created{query.case ? `: ${query.case}` : ""}.</div>}
        {query.error && <div className="mt-5 rounded-xl border border-red-300/20 bg-red-300/5 p-3 text-sm font-bold text-red-200">{query.error.replaceAll("-", " ")}</div>}

        <section className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><Scale size={19} className="text-emerald-300" /><div className="mt-3 text-2xl font-black">{cases.length}</div><div className="text-xs text-slate-500">Recent legal cases</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><LockKeyhole size={19} className="text-amber-300" /><div className="mt-3 text-2xl font-black">{holds.length}</div><div className="text-xs text-slate-500">Active preservation holds</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><FileDown size={19} className="text-sky-300" /><div className="mt-3 text-2xl font-black">{exports.length}</div><div className="text-xs text-slate-500">Recent legal exports</div></div></section>

        <section className="mt-5 grid gap-5 xl:grid-cols-[1fr_1fr]">
          <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-300" /><h2 className="font-black">Open case + preservation hold</h2></div><form action={createLegalCase} className="mt-5 grid gap-3"><input name="title" required placeholder="Case title / reason for preservation" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><div className="grid gap-3 sm:grid-cols-2"><select name="requesterType" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm"><option value="customer">Customer complaint</option><option value="attorney">Attorney request</option><option value="law_enforcement">Law enforcement</option><option value="court">Court / subpoena</option><option value="payment_processor">Payment processor</option><option value="internal">Internal investigation</option></select><input name="requesterName" placeholder="Requester / agency / law firm" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /></div><textarea name="legalAuthority" placeholder="Legal authority, subpoena / warrant / case reference / authorization details" rows={3} className="rounded-xl bg-slate-900 p-3 text-sm" /><div className="grid gap-3 sm:grid-cols-3"><input name="bookingId" placeholder="Booking UUID" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><input name="userId" placeholder="User UUID" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><input name="sessionId" placeholder="Session UUID" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /></div><textarea name="notes" placeholder="Internal notes" rows={3} className="rounded-xl bg-slate-900 p-3 text-sm" /><button className="min-h-11 rounded-xl bg-emerald-400 px-4 text-sm font-black text-slate-950">Create case and preserve records</button></form></article>
          <article className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-2"><FileDown size={18} className="text-emerald-300" /><h2 className="font-black">Generate legal export directly</h2></div><p className="mt-3 text-sm leading-6 text-slate-500">Use one scope. The JSON package includes the linked customer, bookings, provider, evidence metadata, messages, disputes, refunds, transfers, sessions, clickstream when consented, CRM and email history. A SHA-256 manifest is stored with the export event.</p><form action="/api/admin/legal/export" method="get" className="mt-5 grid gap-3"><input name="bookingId" placeholder="Booking UUID (recommended)" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><input name="userId" placeholder="or User UUID" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><input name="sessionId" placeholder="or Session UUID" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><input name="caseReference" placeholder="Optional VeroTask case reference" className="min-h-11 rounded-xl bg-slate-900 px-3 text-sm" /><button className="min-h-11 rounded-xl border border-emerald-400 px-4 text-sm font-black text-emerald-300">Download hashed JSON dossier</button></form><div className="mt-4 rounded-xl border border-amber-300/15 bg-amber-300/5 p-3 text-xs leading-5 text-amber-100/60">VeroTask does not store full card number or CVV. Processor-native records remain with Stripe. IP geolocation is approximate; service GPS evidence is separate.</div></article>
        </section>

        <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="border-b border-white/10 p-5"><h2 className="font-black">Cases</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b border-white/10 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Title</th><th className="px-4 py-3">Requester</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Scope</th><th className="px-4 py-3">Opened</th></tr></thead><tbody className="divide-y divide-white/5">{cases.map((item) => <tr key={item.id}><td className="px-4 py-3 font-mono text-xs font-black text-emerald-300">{item.caseReference}</td><td className="px-4 py-3 font-black">{item.title}</td><td className="px-4 py-3"><div>{item.requesterType.replaceAll("_", " ")}</div><div className="text-xs text-slate-600">{item.requesterName || "--"}</div></td><td className="px-4 py-3"><span className="rounded-full bg-white/5 px-2 py-1 text-[11px] font-black uppercase">{item.status}</span></td><td className="px-4 py-3"><pre className="max-w-[330px] overflow-hidden text-[10px] text-slate-500">{JSON.stringify(item.scope)}</pre></td><td className="px-4 py-3 font-mono text-xs text-slate-500">{item.openedAt.toISOString()}</td></tr>)}</tbody></table></div></section>

        <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="border-b border-white/10 p-5"><h2 className="font-black">Export ledger</h2></div><div className="max-h-[520px] divide-y divide-white/5 overflow-y-auto">{exports.map((item) => <div key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-mono text-xs font-black text-sky-300">{item.manifestHash}</div><div className="mt-1 text-xs text-slate-600">{item.generatedAt.toISOString()} · {item.requestedBy}</div></div><Fingerprint size={16} className="text-slate-600" /></div><pre className="mt-2 overflow-hidden text-[10px] text-slate-500">{JSON.stringify(item.scope)}</pre></div>)}</div></article><article className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"><div className="border-b border-white/10 p-5"><h2 className="font-black">Administrator audit trail</h2></div><div className="max-h-[520px] divide-y divide-white/5 overflow-y-auto">{audit.map((item) => <div key={item.id} className="p-4 text-xs"><div className="flex justify-between gap-3"><strong>{item.action}</strong><span className="font-mono text-slate-600">{item.occurredAt.toISOString()}</span></div><div className="mt-1 text-slate-500">{item.resourceType || "--"} · {item.resourceId || "--"}</div><div className="mt-1 break-all font-mono text-[10px] text-slate-700">hash {item.eventHash}</div></div>)}</div></article></section>
      </div>
    </AdminShell>
  );
}
