import { desc, gte, sql } from "drizzle-orm";
import { getDb } from "@/db";
import { analyticsEvents, visitorSessions } from "@/db/analytics-schema";

export async function AnalyticsBreakdown() {
  const db = getDb();
  const since = sql`now() - interval '30 days'`;
  const [sources, places, pages] = await Promise.all([
    db.select({ source: visitorSessions.utmSource, medium: visitorSessions.utmMedium, campaign: visitorSessions.utmCampaign, referrer: visitorSessions.referrer, visits: sql<number>`count(*)::int` }).from(visitorSessions).where(gte(visitorSessions.startedAt, since)).groupBy(visitorSessions.utmSource, visitorSessions.utmMedium, visitorSessions.utmCampaign, visitorSessions.referrer).orderBy(desc(sql`count(*)`)).limit(12),
    db.select({ city: visitorSessions.city, region: visitorSessions.region, country: visitorSessions.countryCode, visits: sql<number>`count(*)::int` }).from(visitorSessions).where(gte(visitorSessions.startedAt, since)).groupBy(visitorSessions.city, visitorSessions.region, visitorSessions.countryCode).orderBy(desc(sql`count(*)`)).limit(12),
    db.select({ path: analyticsEvents.path,
      views: sql<number>`count(*) filter (where ${analyticsEvents.eventType} = 'page_view')::int`,
      clicks: sql<number>`count(*) filter (where ${analyticsEvents.eventType} = 'click')::int`,
      seconds: sql<number>`coalesce(sum((${analyticsEvents.metadata}->>'durationMs')::numeric) filter (where ${analyticsEvents.eventType} = 'heartbeat'), 0)::int / 1000`,
      scroll: sql<number>`coalesce(max((${analyticsEvents.metadata}->>'scrollDepth')::numeric) filter (where ${analyticsEvents.eventType} = 'scroll_depth'), 0)::int`
    }).from(analyticsEvents).where(gte(analyticsEvents.occurredAt, since)).groupBy(analyticsEvents.path).orderBy(desc(sql`count(*)`)).limit(30)
  ]);
  return <section className="mt-5 space-y-5"><div className="grid gap-5 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 p-5"><h2 className="font-bold">Traffic sources · 30 days</h2><p className="mt-1 text-xs text-slate-400">Source, medium, campaign and referring website.</p><div className="mt-4 divide-y divide-white/10">{sources.map((row, index) => <div key={index} className="flex justify-between gap-4 py-3 text-sm"><div><strong>{row.source || row.referrer || "Direct / unavailable"}</strong><p className="mt-1 break-all text-xs text-slate-400">{[row.medium, row.campaign, row.source && row.referrer].filter(Boolean).join(" · ")}</p></div><strong>{row.visits}</strong></div>)}</div>{!sources.length && <p className="mt-4 text-slate-400">No consented visits yet.</p>}</article><article className="rounded-2xl border border-white/10 p-5"><h2 className="font-bold">Visitor locations · 30 days</h2><p className="mt-1 text-xs text-slate-400">Approximate network location. Localhost has no public visitor geolocation.</p><div className="mt-4 divide-y divide-white/10">{places.map((row, index) => <div key={index} className="flex justify-between gap-4 py-3 text-sm"><span>{[row.city, row.region, row.country].filter(Boolean).join(", ") || "Location unavailable"}</span><strong>{row.visits}</strong></div>)}</div></article></div><article className="overflow-hidden rounded-2xl border border-white/10"><div className="p-5"><h2 className="font-bold">Page engagement · 30 days</h2><p className="mt-1 text-xs text-slate-400">Visible-tab time, measured in intervals. Scroll shows the deepest measured position.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y border-white/10 text-slate-400"><tr>{["Page", "Views", "Clicks", "Active time", "Average / view", "Max scroll"].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{pages.map((row) => <tr key={row.path} className="border-b border-white/5"><td className="p-3">{row.path}</td><td className="p-3">{row.views}</td><td className="p-3">{row.clicks}</td><td className="p-3">{row.seconds}s</td><td className="p-3">{row.views ? Math.round(row.seconds / row.views) : 0}s</td><td className="p-3">{row.scroll}%</td></tr>)}</tbody></table></div></article></section>;
}
