import Link from "next/link";
import { eq } from "drizzle-orm";
import { BadgeCheck, Building2, CalendarClock, CreditCard, LogOut, ShieldCheck, UsersRound } from "lucide-react";
import { redirect } from "next/navigation";
import { isAdminSession } from "@/lib/admin-auth";
import AdminOverview from "@/app/admin/page";
import { getDb } from "@/db";
import { businessClaims, businesses } from "@/db/schema";
import { getCurrentUser, signOut } from "@/lib/auth";

async function logoutAction() { "use server"; await signOut(); redirect("/"); }
export const dynamic = "force-dynamic";

export default async function Page() {
  if (await isAdminSession()) return <AdminOverview />;
  const user = await getCurrentUser();
  if (!user) redirect("/signin?next=/dashboard");
  const db = getDb();
  const owned = await db.select().from(businesses).where(eq(businesses.ownerUserId, user.id));
  const claims = await db.select({ claim: businessClaims, business: businesses }).from(businessClaims).innerJoin(businesses, eq(businesses.id, businessClaims.businessId)).where(eq(businessClaims.claimantUserId, user.id));

  return <main className="min-h-screen">
    <header className="border-b border-[var(--line)] bg-white"><div className="container-shell flex min-h-16 items-center justify-between gap-4"><Link href="/" className="flex items-center gap-2 text-xl font-black"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[var(--brand)] text-white"><BadgeCheck size={20} /></span>VeroTask</Link><form action={logoutAction}><button className="inline-flex items-center gap-2 text-sm font-bold text-[var(--muted)]"><LogOut size={16} /> Sign out</button></form></div></header>
    <section className="container-shell py-10">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[var(--brand)]">ACCOUNT</p><h1 className="mt-1 text-3xl font-black tracking-tight">Welcome{user.name ? `, ${user.name}` : ""}</h1><p className="mt-2 text-sm text-[var(--muted)]">{user.email}</p></div><div className="flex flex-wrap gap-3"><Link href="/dashboard/profile" className="btn-secondary">Your profile</Link><Link href="/dashboard/bookings" className="btn-secondary">Bookings & jobs</Link><Link href="/services" className="btn-secondary">Find my Pro</Link></div></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-3">
        <article className="card p-6 lg:col-span-2"><div className="flex items-center gap-2"><Building2 size={20} className="text-[var(--brand)]" /><h2 className="font-black">{owned.length === 0 ? "What would you like to do?" : "Your businesses"}</h2></div>{owned.length === 0 ? <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-[var(--background)] p-5"><p className="font-black">Need a professional?</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Search local VeroTask pros in Orlando and Central Florida, compare profiles and request a protected quote.</p><Link href="/services" className="btn-primary mt-4">Find my Pro</Link></div><div className="rounded-2xl border border-[var(--line)] p-5"><p className="font-black">Are you a professional?</p><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Create or claim your provider profile to receive structured service opportunities through VeroTask.</p><Link href="/providers/join" className="btn-secondary mt-4">Join as a Pro</Link></div></div> : <div className="mt-5 space-y-3">{owned.map((business) => <div className="rounded-2xl border border-[var(--line)] p-5" key={business.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-black">{business.name}</div><div className="mt-1 text-xs uppercase tracking-wide text-[var(--muted)]">{business.plan} plan · {business.status}</div></div><Link className="text-sm font-black text-[var(--brand)]" href={`/providers/${business.slug}`}>View profile</Link></div><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div className="rounded-xl bg-[var(--background)] p-3"><span className="font-bold">Service payments:</span> paid directly by customers</div><div className="rounded-xl bg-[var(--background)] p-3"><span className="font-bold">VeroTask fee:</span> charged to customer after acceptance</div></div><div className="mt-4 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 text-sm font-black text-[var(--brand)]" href={`/dashboard/providers/${business.id}/customers`}><UsersRound size={16} /> Customer memory</Link><Link className="inline-flex items-center gap-2 text-sm font-black text-[var(--brand)]" href={`/dashboard/providers/${business.id}/availability`}><CalendarClock size={16} /> Availability</Link><Link className="text-sm font-black text-[var(--brand)]" href={`/dashboard/providers/${business.id}/services`}>Services</Link><Link className="text-sm font-black text-[var(--brand)]" href={`/dashboard/providers/${business.id}/billing`}>Plans & billing</Link></div></div>)}</div>}</article>
        <article className="card p-6"><div className="flex items-center gap-2"><ShieldCheck size={20} className="text-[var(--brand)]" /><h2 className="font-black">{owned.length === 0 ? "Protected hiring" : "Trust status"}</h2></div><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{owned.length === 0 ? "Your email, phone and exact service address stay private while a professional reviews your request and prepares a quote. The exact address is released only after the VeroTask booking fee is paid." : "Verified providers can receive booking requests after configuring services and availability. VeroTask does not require Stripe Connect because service payments are made directly to the professional."}</p><Link href="/protection" className="mt-4 inline-flex text-sm font-black text-[var(--brand)]">View protection rules</Link></article>
      </div>
      {claims.length > 0 && <section className="card mt-5 p-6"><h2 className="font-black">Business claims</h2><div className="mt-4 space-y-3">{claims.map(({ claim, business }) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[var(--line)] p-4" key={claim.id}><div><div className="font-bold">{business.name}</div><div className="mt-1 text-xs text-[var(--muted)]">Submitted {claim.createdAt.toLocaleDateString("en-US")}</div></div><span className="badge bg-[var(--background)] text-[var(--muted)]">{claim.status}</span></div>)}</div></section>}
      <section className="mt-5 grid gap-5 md:grid-cols-2"><div className="card p-6"><CreditCard size={20} className="text-[var(--brand)]" /><h2 className="mt-3 font-black">Payments</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Stripe processes the VeroTask booking fee and optional provider subscriptions. Service payments are made directly between customers and professionals.</p></div><Link href="/dashboard/bookings" className="card block p-6 transition hover:-translate-y-0.5"><BadgeCheck size={20} className="text-[var(--brand)]" /><h2 className="mt-3 font-black">Bookings</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">Open customer bookings and provider jobs, including reputation, messages, evidence and dispute status.</p></Link></section>
    </section>
  </main>;
}
